name: Validate commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run commitlint
        if: github.actor != 'dependabot[bot]'
        run: commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run linters
        run: npm run lint:code
      - name: Run tests
        run: npm run test
        env:
          TEST_CLIENT_EMAIL: ${{ secrets.TEST_CLIENT_EMAIL }}
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          TEST_SUBSCRIPTIONS_URLS: ${{ secrets.TEST_SUBSCRIPTIONS_URLS }}
